### ISSUE TITLE
Not working with nextjs (client side rendering)

### ISSUE THREAD

**Issue by yojona** [huozhi/respinner#23]
im using version 3.0.5
![image](https://user-images.githubusercontent.com/13840865/149646973-140b0df8-51fe-4998-a78f-9619ec4da091.png)
![image](https://user-images.githubusercontent.com/13840865/149646982-9da70c0f-4d5f-4220-9418-182359e0e6c0.png)

also, props are not available in the autocomplete, the editor shows this: 
![image](https://user-images.githubusercontent.com/13840865/149646955-69628fb7-2cdc-45a7-aba2-fd4e71367a22.png)

**Comment by huozhi** [comment]
@yojona Thanks for reporting! could you try the new version 3.0.6? Should be fixed now 🙏

**Comment by yojona** [comment]
@huozhi  works great! thank you!
